router:
  host: "127.0.0.1"
  port: "8021"
booking_service:
  host: "bookingservice"
  port: 50051
auth_service:
  host: "authservice"
  port: 50051
rabbit:
  login: "guest"
  password: "guest"
  host: "rabbit"
  port: "5672"
  channel: "orders"